knezicm/pds-2022

LTamara1013/test.vhd

Dodavanje testnog fajla (VHDL kod za ILI logicko kolo).

Issue #28 : Dodavanje testnog fajla

---

JovanaAre/test.vhd

- Created folder with user name
- Added test file

Issue #32 : Added test files

---

jovanabozic/test.vhd

-kreiranje git okruzenja, kreiranje grane, kreiranje pull request

predaja testnog vhd fajla

---

assignments/43/four_bit_full_adder.vhd
assignments/43/one_bit_full_adder.vhd

…description
- Added entity definition for the design of one-bit full adder
- Added initial code for architecture using basic logic gates
- Added entity definition for the design of four-bit full adder
- Added initial code for architecture using structural description

Issue #43 : Design four-bit full adder (first method)

---

assignments/46/four_bit_full_subtractor.vhd
assignments/46/one_bit_full_subtractor.vhd

-Added entity definition for the design of four-bit-full-subtractor 
-Added entity definition for the design of one-bit-full-subtractor 
-Added initial code for one-bit-full-subtractor and four-bit-full-subtractor architecture

Issue #46 : Create full-subtractor circuit (first method)

---

assignments/49/four_bit_comparator.vhd
assignments/49/two_bit_comparator.vhd

- Added entity definition for the design of two-bit comparator
- Added initial code for architecture using structural description"

 Issue #49: Create four-bit comparator 

---

assignments/53/decoder_2_4.vhd

- Added entity definition for 2-4 decoder
- Added code for architecture using With-Select concurrent statement

Issue #53 : Create 2-4 decoder with enable input (third method)

---

assignments/47/four_bit_full_subtractor.vhd
assignments/47/full_sub.vhd

Postovanje profesore,
Popravila sam kod. Greska je bila u tome, sto biti ulaznog vektora nisu mapirani jedan za drugim. Ovaj error nije bio prisutan na
Alterinom kompajleru, koji sam ja skinula. Tako da nisam ni obratila paznju na gresku. Takodjer, dodala sam Vas kao rewievera.

 Issue #47 : full-subtractor circuit (second method)

---

assignments/83/four_bit_lzc.vhd
assignments/83/four_bit_lze.vhd
assignments/83/leading_zero_counter_unit.vhd
assignments/83/leading_zero_counter_unit_tb.vhd

Created 4-bit leading zero counter
Created 4 bit leading zero encoder
Created 16-bit leading zero counter
Created testbench for 16-bit LZC
Tested on all possible combinations

Issue #83 : Create Leading Zero Counter

---

assignments/81/hamming_distance_unit.vhd
assignments/81/hamming_distance_unit_tb.vhd
assignments/81/hamming_distance_unit_tb.vht

- Added hamming_distance_unit.vhd
- Added hamming_distance_unit_tb.vht

Issue #81 : Create Hamming distance circuit

---

assignments/75/seven_bit_comparator.vhd
assignments/75/signed_to_sign_magnitude_converter.vhd
assignments/75/signed_to_sign_magnitude_converter_tb.vhd

-Added seven bit comparator
-Added signed to sign-magnitude converter
-Added testbench file for signed to sign-magnitude converter

Issue #75 : Create circuit for converting signed to sign-magnitude number

---

assignments/104/preamble_detector.vhd
assignments/104/preamble_detector_tb.vhd
assignments/104/preamble_detector_vhd_tst.vhd

- Added entity definition for the design
- Created an initial testbench code for the design
- Added documentation with doxygen tool

 Issue #104: Design preamble-detector

---

assignments/103/preamble_generator.vhd
assignments/103/preamble_generator_tb.vhd

- Added entity for design
- Added tesbench file for preamble generator entity

Issue #103 : Create preamble generator

---

assignments/107/nrzi_decoder.vhd
assignments/107/nrzi_decoder_tb.vhd

Created testbench
Tested
Written doxygen comments
Formated

Issue #107: Created NRZI decoder

---

assignments/80/decoder_3_8.vhd
assignments/80/dual_code_priority_encoder.vhd
assignments/80/dual_code_priority_encoder_tb.vhd
assignments/80/priority_encoder_8_3.vhd

- Added entity definition for the design of 8 to 3 priority encoder
- Added initial code for architecture using if-else statement
- Added entity definition for the design of 3 to 8 decoder
- Added initial code for architecture using case statement
- Added entity definition for the design of dual-code priority encoder
- Added initial code for architecture using structural description
- Created selfchecking testbench file for dual-code priority encoder

Issue #80 : Create dual-code priority encoder

---

assignments/82/three_mode_barrel_shifter.vhd
assignments/82/three_mode_barrel_shifter_tb.vhd

- Added entity definition for the design of three-mode barrel shifter
- Created (self-checking) testbench file for three-mode barrel shifter
- Design rules checked

Issue #82 : Create three-mode barrel shifter

---

assignments/101/dual_edge_detector.vhd
assignments/101/dual_edge_detector_tb.vhd

- Added entity definition for the design using Moore FSM
- Created an initial testbench code for the design

Issue #101 : Create dual-edge detector circuit using Moore FSM

---

assignments/79/eight_bit_multiplier.vhd
assignments/79/eight_bit_multiplier_tb.vhd

Added entity definition for the design
Added initial code for architecture
Created an initial testbench code for the design

 Issue #79: Design eight-bit multiplier

---

assignments/98/manchester_encoder.vhd
assignments/98/manchester_encoder_tb.vhd

- Added entity definition for the design of Manchester encoder
- (self-checking) testbench file for Manchester encoder created

Issue #98 : Create Manchester encoding circuit

---

assignments/106/nrzi_encoder.vhd
assignments/106/nrzi_encoder_tb.vhd

- Issue #106 : Create NRZI encoding circuit 
-Adding entity nrzi_encoder
-Adding testbench nrzi_encoder_tb

Issue #106 : Nrzi encoding circuit

---

assignments/121/sequential_divider.sdc
assignments/121/sequential_divider.vhd
assignments/121/sequential_divider_tb.vhd

Implemented with FSM, data and control path
Writen .sdc file

Issue #121: Create sequential divider using long-division algorithm

---

assignments/122/fibonacci.sdc
assignments/122/fibonacci.vhd
assignments/122/fibonacci_tb.vhd

- Added entity for design (fibbonaci.vhd)
- Added fibbonaci.sdc file

Issue #122 : Create Fibonacci sequence generator

---

assignments/123/leading_zero_counter.sdc
assignments/123/leading_zero_counter.vhd
assignments/123/leading_zero_counter_tb.vhd

- Added entity definition for the design
- Added .sdc file

Issue #123 : Create leading zero counter circuit (FSMD approach)
